# Generated by Django 2.2.1 on 2019-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://s.dicio.com.br/algum.jpg', upload_to='institute/', verbose_name='Imagem'),
        ),
    ]
