# Generated by Django 2.2.1 on 2019-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='algum.jpg', upload_to='institute/', verbose_name='Imagem'),
        ),
    ]
